name: Hello World Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: echo "Hello World from git actions project"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Goodbye World
        run: echo "Goodbye World from git actions project"
        shell: bash
      - name: Thanks to Teacher
        run: echo "Thank you for teaching me about vs code"

